routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return 'OK';
});

Route::get('/app-check', function () {
    $fails = [];

    try {
        Illuminate\Support\Facades\Redis::connection('default');
    } catch (RedisException $e) {
        $fails[] = 'REDIS';

        Log::channel('healthcheck')->error($e->getMessage());
    }
    try {
        DB::connection()
            ->table('migrations')
            ->where('id', '>', 1)
            ->where('id', '<', 10)
            ->first();
    } catch (\Exception $e) {
        $fails[] = 'DB';
        Log::channel('healthcheck')->error($e->getMessage());
    }
    try {
        $body = Http::get('https://ws.e-hallpass.com/')->body();
        if ($body !== 'OK') {
            $fails[] = 'SOCKET';
        }
    } catch (\Exception $e) {
        $fails[] = 'SOCKET';

        Log::channel('healthcheck')->error($e->getMessage());
    }

    return !count($fails) ? 'OK' : response()->json(['fails' => $fails], 500);
});

Route::get('/socketTest', function () {
    event(new \App\Events\TestEvent('hello'));
});

Route::group(
    ['middleware' => 'horizonBasicAuth', 'prefix' => 'api/v5/cross-check'],
    function () {
        Route::get('/schools/{school}', 'Admin\Misc\CrossCheckController@schoolShow')->name(
            'api.v5.crosscheck.schools.show'
        );
        Route::get('/schools', 'Admin\Misc\CrossCheckController@schools')->name(
            'api.v5.crosscheck.schools.index'
        );
        Route::get('/schools/{school}/verify/{status}', 'Admin\Misc\CrossCheckController@verifySchool')->name(
            'api.v5.crosscheck.schools.verify'
        );
        Route::get('/schools/{school}/image', 'Admin\Misc\CrossCheckController@migrateImage')->name(
            'api.v5.crosscheck.schools.image'
        );
        Route::get('/schools/{school}/modules', 'Admin\Misc\CrossCheckController@migrateModule')->name(
            'api.v5.crosscheck.schools.modules'
        );

        Route::get('/', 'Admin\Misc\CrossCheckController@index')->name('api.v5.crosscheck.index');
        Route::get('/{school}', 'Admin\Misc\CrossCheckController@show')->name(
            'api.v5.crosscheck.show'
        );
        Route::get('/{school}/migrate/{oldId}', 'Admin\Misc\CrossCheckController@migrate')->name(
            'api.v5.crosscheck.migrate'
        );
        Route::get('/{school}/migrateAll', 'Admin\Misc\CrossCheckController@migrateAll')->name(
            'api.v5.crosscheck.migrateAll'
        );
        Route::get('/{school}/verify/{status}', 'Admin\Misc\CrossCheckController@verify')->name(
            'api.v5.crosscheck.verify'
        );
        Route::get('/{school}/delete/{user}', 'Admin\Misc\CrossCheckController@delete')->name(
            'api.v5.crosscheck.delete'
        );
        Route::get('/{school}/deleteCus/{membership}', 'Admin\Misc\CrossCheckController@deleteMembership')->name(
            'api.v5.crosscheck.deleteMembership'
        );
        Route::get('/{school}/deleteAll/{ids}', 'Admin\Misc\CrossCheckController@deleteAll')->name(
            'api.v5.crosscheck.deleteAll'
        );
        Route::get('/{school}/sync/{memberships}', 'Admin\Misc\CrossCheckController@sync')->name(
            'api.v5.crosscheck.sync'
        );
        Route::get('/{school}/deleteAllCus/{memberships}', 'Admin\Misc\CrossCheckController@deleteAllCus')->name(
            'api.v5.crosscheck.deleteAllCus'
        );
        Route::get('/{school}/syncwithv1/{user}', 'Admin\Misc\CrossCheckController@syncwithv1')->name(
            'api.v5.crosscheck.syncwithv1'
        );


    }
);

app/Models/School.php
<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Cache;
use Illuminate\Support\Facades\Storage;

class School extends Model implements PushNotifications
{
    use HasFactory;

    public const PERMISSION_ACTIVE = 1;
    public const PERMISSION_INACTIVE = 0;
    public const SCHOOL_IMAGE_DIRECTORY = 'schoolimage/';

    protected $appends = [
        'active_modules',
        'hide_student_kiosk_password_field',
        'active_domains',
        'show_photos',
        'active_school'
    ];

    protected $hidden = [
        'avatar_api',
        'total_user_role',
        'is_sftp_image',
        'csv_roles',
        'csv_headers',
        'archive_prefix',
        'upload_folder',
        'total_users',
        'if_username',
        'is_user_csv',
        'is_manual',
        'timezone_offset',
        'stop_status',
        'webservice',
        'api_key'
    ];

    protected $casts = [
        'auth_providers' => 'array'
    ];

    protected $with = ['modules'];

    protected $guarded = ['id'];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function rooms()
    {
        return $this->hasMany(Room::class);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function schoolUser(): \Illuminate\Database\Eloquent\Relations\BelongsToMany
    {
        return $this->belongsToMany(User::class, 'schools_users')->withPivot(
            'school_id'
        );
    }

    /**
     * @param int|null $schoolId
     * @return mixed
     */
    public static function findCacheFirst(?int $schoolId)
    {
        if ($schoolId === null) {
            return null;
        }

        return Cache::remember(
            'school_' . $schoolId,
            now()->addMinutes(5),
            function () use ($schoolId) {
                return self::whereId($schoolId)
                    ->setEagerLoads([])
                    ->select(['timezone', 'id', 'timezone_offset'])
                    ->first()
                    ->setAppends([]);
            }
        );
    }

    /**
     * @return bool
     */
    public function getHideStudentKioskPasswordFieldAttribute(): bool
    {
        $moduleKiosk = $this->modules()
            ->wherePivot('status', 1)
            ->where('name', Module::KIOSK)
            ->first();
        if ($moduleKiosk) {
            $kioskPasswordFieldFlag = json_decode(
                optional($moduleKiosk)->pivot->option_json
            );
            if ($kioskPasswordFieldFlag !== null) {
                return (bool) optional($kioskPasswordFieldFlag)->spassword;
            }
        }
        return false;
    }

    /**
     * @param $moduleName
     * @return bool
     */
    public function hasModule($moduleName)
    {
        return $this->modules->pluck('name')->contains($moduleName);
    }

    public function getActiveModulesAttribute(): \Illuminate\Support\Collection
    {
        return $this->modules()
            ->wherePivot('status', 1)
            ->pluck('name');
    }

    public function getActiveDomainsAttribute(): \Illuminate\Support\Collection
    {
        return $this->domains()->pluck('name');
    }

    public function getShowPhotosAttribute()
    {
        return $this->show_student_photos && $this->hasStudentsWithPhotos();
    }

    public function hasStudentsWithPhotos()
    {
        return $this->students()
            ->whereNotNull('avatar')
            ->exists();
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function passes()
    {
        return $this->hasMany(Pass::class);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function roomTypes()
    {
        return $this->hasMany(RoomType::class);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function autoPassesLimits()
    {
        return $this->hasMany(AutoPassLimit::class);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function autoPasses()
    {
        return $this->hasMany(AutoPass::class);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function blockPasses()
    {
        return $this->hasMany(BlockPass::class);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function locationCapacities()
    {
        return $this->hasMany(LocationCapacity::class);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\MorphMany
     */
    public function passLimits()
    {
        return $this->morphMany(PassLimit::class, 'limitable');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function restrictions()
    {
        return $this->hasMany(RoomRestriction::class);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function pinAttempts()
    {
        return $this->hasMany(PinAttempt::class);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function pins()
    {
        return $this->hasMany(Pin::class);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function staffSchedules()
    {
        return $this->hasMany(StaffSchedule::class);
    }

    /**
     * @param $date
     * @param string|null $timezone
     * @param bool $onlyDate
     * @param bool $onlyTime
     * @param string|null $format
     * @return string|null
     */
    public static function convertTimeToCorrectTimezone(
        $date,
        ?string $timezone,
        bool $onlyDate = false,
        bool $onlyTime = false,
        ?string $format = null
    ): ?string {
        if ($timezone === null) {
            return $date;
        }

        $onlyDateFormat = Carbon::parse($date, config('app.timezone'))->format(
            $format === null ? 'Y-m-d' : $format
        );
        $dateFormatted = !$onlyDate
            ? Carbon::parse($date, config('app.timezone'))
                ->setTimezone($timezone)
                ->format($format === null ? 'Y-m-d H:i:s' : $format)
            : $onlyDateFormat;

        if ($onlyTime) {
            $dateFormatted = Carbon::parse($date, config('app.timezone'))
                ->setTimezone($timezone)
                ->format('g:i A');
        }

        return $date !== null ? $dateFormatted : null;
    }

    /**
     * @param $date
     * @param string $timezone
     * @return string|null
     */
    public static function convertSchoolDatesToUTC($date, string $timezone)
    {
        return $date !== null
            ? Carbon::parse($date, $timezone)
                ->setTimezone(config('app.timezone'))
                ->format('Y-m-d H:i:s')
            : null;
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function passBlocks()
    {
        return $this->hasMany(PassBlock::class);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasOne
     */
    public function activePassBlock(): \Illuminate\Database\Eloquent\Relations\HasOne
    {
        return $this->hasOne(PassBlock::class)
            ->where('students', 1)
            ->where('from_date', '<=', now())
            ->where('to_date', '>=', now());
    }

    public function domains()
    {
        return $this->hasMany(Domain::class);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function users()
    {
        return $this->hasMany(User::class);
    }

    public function students(): \Illuminate\Database\Eloquent\Relations\HasMany
    {
        return $this->hasMany(User::class)->where(
            'role_id',
            Role::getRoleIdByName(User::Student)
        );
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function appointmentPasses()
    {
        return $this->hasMany(AppointmentPass::class);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function transparencies()
    {
        return $this->hasMany(Transparency::class);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function transparencyUsers()
    {
        return $this->hasMany(TransparencyUser::class);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function modules()
    {
        return $this->belongsToMany(Module::class, 'school_modules')
            //            ->wherePivot('status', Module::ACTIVE)
            ->withPivot('permission', 'option_json', 'status');
    }

    /**
     * @param $moduleName
     * @return mixed
     */
    public function getModuleOptions($moduleName)
    {
        $pivotModuleOptions = optional(
            $this->modules()
                ->where('name', $moduleName)
                ->wherePivot('status', Module::ACTIVE)
                ->first()
        )->pivot;

        return optional($pivotModuleOptions)->option_json !== null
            ? $pivotModuleOptions->option_json
            : null;
    }

    /**
     * @return mixed|null
     */
    public function getTimezone()
    {
        return $this->timezone;
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function globalPassLimits()
    {
        return $this->hasMany(ActivePassLimit::class);
    }

    /**
     * @param $value
     * @return string|null
     */
    public function getLogoAttribute($value): ?string
    {
        if (!$value) {
            return null;
        }

        if (
            !Storage::disk('s3')->exists(self::SCHOOL_IMAGE_DIRECTORY . $value)
        ) {

app/Http/Controllers/Admin/Schools/SchoolController.php
<?php

namespace App\Http\Controllers\Admin\Schools;

use App\Http\Controllers\Controller;
use App\Models\School;
use App\Models\User;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

/**
 * @group School manage (Admin/Teacher/Staff)
 */
class SchoolController extends Controller
{
    /**
     * Change user current school.
     *
     * @urlParam school integer required The id of the school.
     *
     * @response status=200 scenario="Successful change" {
     *      "data": {
     *          "school_id": 1
     *      }
     *      "status": "success"
     * }
     *
     * @response status=403 scenario="Undefined school." {
     *      "data": {
     *          "school_id": 1
     *      },
     *      "message": "invalid.school.for.change"
     *      "status": "fail"
     * }
     *
     * @param School $school
     * @return JsonResponse
     */
    public function change(School $school)
    {
        $schoolId = $school->id;

        $membership = DB::table('schools_users')->where([
            'user_id' => auth()->user()->id,
            'school_id' => $schoolId
        ])->first();

        //Update the assigned school.
        if ($membership) {
            $roleId = $membership->role_id ?? auth()->user()->role_id;
            $updateUserSchool = auth()->user()->update([
                'school_id' => $schoolId,
                'role_id' => $roleId
            ]);

            return response()->json([
                'data' => [
                    'school_id' => $schoolId,
                    'role_id' => $membership->role_id
                ],
                'status' => __('success')
            ]);
        }

        return response()->json([
            'data' => ['school_id' => $schoolId],
            'message' => __('invalid.school.for.change'),
            'status' => __('fail')
        ], 403);

    }
}

resources/views/misc/schools/index.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Cross check | E-Hallpass V2</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.tailwindcss.com"></script>
</head>

<body class="inset-0">
<div class="flex flex-nowrap justify-center content-center m-2">
    <div class="container m-0">
        {{ $schools->links() }}
        <div class="flex flex-nowrap justify-center m-2">
            <div class="container m-0">
                <div class="grid grid-cols-1 gap-2">
                    <div class="box-border shadow-lg rounded border-solid w-128 h-128 bg-cyan-500 text-center">
                        <div class="content">
                            <h1 class="text-stone-300">V1 Schools</h1>

                            <hr class="mt-2"/>
                            <form class="pt-2 relative mx-auto text-gray-600">
                                <input
                                    class="border-2 border-gray-300 bg-white h-10 px-5 pr-2 rounded-lg text-sm focus:outline-none"
                                    type="search" name="search" placeholder="Search">
                                <button type="submit" class="absolute right-0 top-0 mt-5 mr-4">
                                    <svg class="text-gray-600 h-4 w-4 fill-current" xmlns="http://www.w3.org/2000/svg"
                                         xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" id="Capa_1" x="0px"
                                         y="0px"
                                         viewBox="0 0 56.966 56.966" style="enable-background:new 0 0 56.966 56.966;"
                                         xml:space="preserve"
                                         width="512px" height="512px">
            <path
                d="M55.146,51.887L41.588,37.786c3.486-4.144,5.396-9.358,5.396-14.786c0-12.682-10.318-23-23-23s-23,10.318-23,23  s10.318,23,23,23c4.761,0,9.298-1.436,13.177-4.162l13.661,14.208c0.571,0.593,1.339,0.92,2.162,0.92  c0.779,0,1.518-0.297,2.079-0.837C56.255,54.982,56.293,53.08,55.146,51.887z M23.984,6c9.374,0,17,7.626,17,17s-7.626,17-17,17  s-17-7.626-17-17S14.61,6,23.984,6z"/>
          </svg>
                                </button>
                            </form>
                            <br/>
                            <table class="table-auto rounded bg-slate-600 min-w-full text-white text-left">
                                <thead class="bg-slate-500">
                                <tr>
                                    <th class="bg-slate-600">#</th>
                                    <th class="bg-slate-600">ID</th>
                                    <th>School Name</th>
                                </tr>
                                </thead>
                                <tbody>
                                @php
                                    $i = 1;
                                @endphp

                                @foreach($schools as $school)
                                    @if(!empty($school->school_name))
                                        <tr>
                                            <td class="bg-slate-600">{{ $i++ }}</td>
                                            <td class="bg-slate-600">{{ $school->school_id }}</td>
                                            <td>
                                                <a href="{{route('api.v5.crosscheck.schools.show', ['school' => $school->school_id])}}">{{$school->school_name}} </a>
                                            </td>
                                        </tr>
                                    @endif
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</body>
</html>

resources/views/misc/schools/show.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Cross check | E-Hallpass V2</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.tailwindcss.com"></script>
</head>

<body class="inset-0">
<div class="flex flex-nowrap justify-center justify-around  m-8">
    <div class="container m-0">
        <div class="grid grid-cols-2 gap-2">

            <div class="box-border shadow-lg rounded border-solid w-128 h=128 bg-cyan-500 grid grid-cols-2 gap-2">
                <div class="content pl-6 pt-2 pr-6">
                    <h1 class="text-stone-100">V1</h1>

                    <p>{{$oldSchool->school_id}}</p>
                    <p>{{$oldSchool->school_name}}</p>
                    <p>{{$oldSchool->school_domain}} | {{$oldSchool->student_domain}}</p>
                    <p>Status {{$oldSchool->status? 'Active' : 'Inactive'}}</p>
                    <p>Description {{$oldSchool->description}}</p>

                    <ul>
                        @foreach($oldSchool->modules as $module)
                            <li>{{$module['name']}} - {{$module['status']? 'Active' : 'Inactive'}}</li>
                        @endforeach
                    </ul>

                </div>
                <div class="content pl-6 pt-2 pr-6">
                    <p>
                        <img width="100" src="{{$oldSchool->logo}}" alt="">
                    </p>
                    @if($school)
                        <h1 class="text-stone-100">V1 Users</h1>
                        <p>Admin - {{$v1Counters->admin}}</p>
                        <p>Teacher - {{$v1Counters->teacher}}</p>
                        <p>Staff - {{$v1Counters->staff}}</p>
                        <p>Student - {{$v1Counters->student}}</p>
                    @endif
                </div>
            </div>
            <div class="box-border shadow-lg rounded border-solid w-128 h=128 bg-cyan-500 grid grid-cols-2 gap-2">
                @if($school)
                    <div class="content pl-6 pt-2 pr-6">
                        <h1 class="text-stone-100">V2</h1>

                        <p>{{$school->id}} | {{$school->cus_uuid}} </p>
                        <p>{{$school->name}}</p>
                        <p>
                            @foreach($school->domains as $domain)
                                {{$domain->name}} |
                            @endforeach
                        </p>
                        <p>Status {{$school->status? 'Active' : 'Inactive'}}</p>
                        <p>Description {{$school->description}} | Zip: {{$school->zip}} | State: {{$school->state}} </p>
                        <ul>
                            @foreach($v2Modules as $module)
                                <li>{{$module->module->display_name}}
                                    - {{$module->status? 'Active' : 'Inactive' }}</li>
                            @endforeach
                        </ul>
                    </div>
                    <div class="content pl-6 pt-2 pr-6">
                        <p>
                            <img width="100" src="{{$school->logo}}" alt="">
                        </p>
                        <h1 class="text-stone-100">V2 Users</h1>
                        <p>Admin - {{$v2Counters->admin}}</p>
                        <p>Teacher - {{$v2Counters->teacher}}</p>
                        <p>Staff - {{$v2Counters->staff}}</p>
                        <p>Student - {{$v2Counters->student}}</p>
                    </div>
                @endif
            </div>


        </div>
    </div>
</div>
<hr/>
<div class="flex flex-nowrap justify-center justify-around  m-8">
    <div class="container m-0">
        <div>

            <div class="box-border shadow-lg rounded border-solid w-128 h=128 bg-cyan-500 py-3">
                <div class="content pl-6 pt-2 pr-6">
                    <h1 class="text-stone-100">Actions</h1>

                    <br>
                    <p class="mt-3 mb-10">

                        <a class="bg-transparent py-2 px-4 border border-blue-500 rounded"
                           href="{{route('api.v5.crosscheck.schools.verify',[$oldSchool,1])}}">Mark Ready</a>

                        <a class="bg-transparent py-2 px-4 border border-blue-500 rounded"
                           href="{{route('api.v5.crosscheck.schools.verify',[$oldSchool,0])}}">Mark Not Ready</a>
                        @if($school)
                            <a class="bg-transparent py-2 px-4 border border-blue-500 rounded"
                               href="{{route('api.v5.crosscheck.schools.image',$oldSchool)}}">Migrate Image</a>
                            <a class="bg-transparent py-2 px-4 border border-blue-500 rounded"
                               href="{{route('api.v5.crosscheck.schools.modules',$oldSchool)}}">Migrate Modules</a>

                            <a class="bg-transparent py-2 px-4 border border-blue-500 rounded"
                               href="{{route('api.v5.crosscheck.show',$school->id)}}" target="_blank">User Details</a>

                            <a class="bg-transparent py-2 px-4 border border-blue-500 rounded"
                               href="{{route('api.v5.crosscheck.migrateAll',[$school->id])}}">Migrate All Users</a>
                        @endif

                    </p>

                </div>
            </div>
        </div>
    </div>
</div>

<!-- V1 -->
<div class="results m-10">
    @if (session()->has('message'))
        <div class="flex flex-nowrap justify-center m-2">
            {!! json_encode(session()->get('message')) !!}
        </div>
    @endif
</div>
<hr/>

</body>
</html>